#!/bin/bash

echo
echo    mea-startup is a script to open the windows needed for running Meabench.
echo    Douglas Bakkum, 2010
echo
echo    Notes:
echo -- To start getting data into Meabench, connect a chip and start streaming data to the server. Then set the \'slot\' and type \'run\' in mea-nssrv.
echo -- Type a \'?\' to get a list of Meabench commands for each module.
echo -- Push the \'center\' button on the scope to center the recorded voltage traces.
echo -- Use the CmdGui to set chip and configuration parameters.
echo -- After setting a configuration, push the \'arrange\' button and de-select the \'box\' checkbox in mea-scope to see the configured electrode arrangement.
echo
echo

# export LD_LIBRARY_PATH=/usr/local/hima/meabench/current/lib/:$LD_LIBRARY_PATH

gnome-terminal --geometry=60x10+0+20   --hide-menubar -e ./replay/mea_replay &
gnome-terminal --geometry=60x10+0+230    --hide-menubar -e ./spikesrv/mea_spikedet &
gnome-terminal --geometry=60x10+0+440    --hide-menubar -e ./robot/mea_robot &
gnome-terminal --geometry=60x10+0+650    --hide-menubar -e ./scope/mea_scope &


#gnome-terminal --geometry=30x20+1700+450 --hide-menubar -x FPGAterminal &
#gnome-terminal --geometry=30x5+1700+1000 --hide-menubar -x CmdGui &

#cd /<path_to_storage_directory>/ntk/
#gnome-terminal --geometry=30x3+1700+370  --hide-menubar -x server &


